# CREATE TABLE IF NOT EXISTS TM_BATCH_EXECUTE
# (
#     NEXT_BATCH_NO          BIGINT COMMENT '下次执行的批次号',
#     CURR_BATCH_NO          BIGINT COMMENT '正在执行的批次号',
#     LAST_BATCH_NO          BIGINT COMMENT '上次执行的批次号',
#     CREATED_DATETIME       DATETIME NOT NULL COMMENT '创建时间',
#     LAST_MODIFIED_DATETIME DATETIME NOT NULL COMMENT '修改时间'
# ) COMMENT = '执行';

CREATE TABLE IF NOT EXISTS TM_HOUSE
(
    ID                     BIGINT AUTO_INCREMENT COMMENT 'ID',
    DETAIL_URL             VARCHAR(256),
    TITLE                  VARCHAR(256),
    GOOD_HOUSE_TAG         VARCHAR(32),
    XIAO_QU_URL            VARCHAR(256),
    XIAO_QU_NAME           VARCHAR(64),
    SMALL_REGION           VARCHAR(32),
    REGION                 VARCHAR(32),
    PRICE_LEVEL            VARCHAR(16),
    HOUSE_INFO             VARCHAR(256),
    FOLLOW_INFO            VARCHAR(128),
    TAX_FREE               VARCHAR(64),
    SUBWAY                 VARCHAR(32),
    TOTAL_PRICE            VARCHAR(32),
    UNIT_PRICE             VARCHAR(32),
    CREATED_DATETIME       DATETIME NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_DATETIME DATETIME NOT NULL COMMENT '修改时间',
    TO_LEX_MINUTES         INT,
    TO_CECI_MINUTES        INT,
    BATCH_NO               INT,
    REMARK                 VARCHAR(200),
    HOUSE_TYPE             VARCHAR(32) COMMENT '房屋户型',
    STOREY                 VARCHAR(32) COMMENT '所在楼层',
    COVERED_AREA           VARCHAR(32) COMMENT '建筑面积',
    HOUSE_TYPE_STRUCTURE   VARCHAR(32) COMMENT '户型结构',
    INSIDE_FLOOR_AREA      VARCHAR(32) COMMENT '套内面积',
    BUILDING_TYPE          VARCHAR(32) COMMENT '建筑类型',
    ORIENTATION            VARCHAR(32) COMMENT '房屋朝向',
    BUILDING_STRUCTURE     VARCHAR(32) COMMENT '建筑结构',
    DECORATION             VARCHAR(32) COMMENT '装修情况',
    TIHU_RATIO             VARCHAR(32) COMMENT '梯户比例',
    HAS_ELEVATOR           VARCHAR(32) COMMENT '配备电梯',
    HANG_OUT_TIME          VARCHAR(32) COMMENT '挂牌时间',
    TRANSACTION_OWNERSHIP  VARCHAR(32) COMMENT '交易权属',
    LAST_TRANSACTION_TIME  VARCHAR(32) COMMENT '上次交易',
    HOUSE_USAGE            VARCHAR(32) COMMENT '房屋用途',
    HOUSE_YEAR             VARCHAR(32) COMMENT '房屋年限',
    EQUITY_OWNERSHIP       VARCHAR(32) COMMENT '产权所属',
    PLEDGE                 VARCHAR(128) COMMENT '抵押信息',
    PREMISES_PERMIT_SPARE  VARCHAR(32) COMMENT '房本备件',
    IMAGE                  text COMMENT '图片',
    PRIMARY KEY (ID)
) COMMENT = '房屋信息';

CREATE TABLE IF NOT EXISTS TM_HOUSE_LOU_PAN
(
    ID                         VARCHAR(64),
    ITEM_TYPE                  VARCHAR(64),
    ITEM_TYPE_DESC             VARCHAR(64),
    PID                        VARCHAR(64),
    CITY_ID                    VARCHAR(64),
    CITY_NAME                  VARCHAR(64),
    COVER_PIC                  VARCHAR(256),
    MIN_FRAME_AREA             VARCHAR(64),
    MAX_FRAME_AREA             VARCHAR(64),
    DISTRICT_NAME              VARCHAR(64),
    DISTRICT                   VARCHAR(64),
    DISTRICT_ID                VARCHAR(64),
    BIZCIRCLE_ID               VARCHAR(64),
    BIZCIRCLE_NAME             VARCHAR(64),
    BUILD_ID                   VARCHAR(64),
    PROCESS_STATUS             VARCHAR(64),
    RESBLOCK_FRAME_AREA        VARCHAR(64),
    RESBLOCK_FRAME_AREA_RANGE  VARCHAR(64),
    RESBLOCK_FRAME_AREA_DESC   VARCHAR(64),
    DECORATION                 VARCHAR(64),
    LONGITUDE                  VARCHAR(64),
    LATITUDE                   VARCHAR(64),
    FRAME_ROOMS_DESC           VARCHAR(64),
    TITLE                      VARCHAR(64),
    RESBLOCK_NAME              VARCHAR(64),
    RESBLOCK_ALIAS             VARCHAR(256),
    ADDRESS                    VARCHAR(256),
    STORE_ADDR                 VARCHAR(64),
    AVG_UNIT_PRICE             VARCHAR(64),
    AVERAGE_PRICE              VARCHAR(64),
    ADDRESS_REMARK             VARCHAR(256),
    PROJECT_NAME               VARCHAR(64),
    HOUSE_TYPE                 VARCHAR(64),
    HOUSE_TYPE_VALUE           VARCHAR(64),
    SALE_STATUS                VARCHAR(64),
    HAS_EVALUATE               VARCHAR(64),
    HAS_VR_HOUSE               VARCHAR(64),
    HAS_SHORT_VIDEO            VARCHAR(64),
    OPEN_DATE                  VARCHAR(64),
    HAS_VIRTUAL_VIEW           VARCHAR(64),
    LOWEST_TOTAL_PRICE         VARCHAR(64),
    SHOW_PRICE                 VARCHAR(64),
    SHOW_PRICE_UNIT            VARCHAR(64),
    SHOW_PRICE_DESC            VARCHAR(64),
    SHOW_PRICE_CONFIRM_TIME    VARCHAR(64),
    PRICE_CONFIRM_TIME         VARCHAR(64),
    STATUS                     VARCHAR(64),
    SUBWAY_DISTANCE            VARCHAR(64),
    IS_COOPERATION             VARCHAR(64),
    EVALUATE_STATUS            VARCHAR(64),
    SHOW_PRICE_INFO            VARCHAR(64),
    BRAND_ID                   VARCHAR(64),
    REFERENCE_AVG_PRICE        VARCHAR(64),
    REFERENCE_AVG_PRICE_UNIT   VARCHAR(64),
    REFERENCE_AVG_PRICE_DESC   VARCHAR(64),
    REFERENCE_TOTAL_PRICE      VARCHAR(64),
    REFERENCE_TOTAL_PRICE_UNIT VARCHAR(64),
    REFERENCE_TOTAL_PRICE_DESC VARCHAR(64),
    IS_FOLLOWED                VARCHAR(64),
    IS_SUPPORT_ONLINE_SALE     VARCHAR(64),
    IS_UNDERTAKE               VARCHAR(64),
    PROPERRIGHT                VARCHAR(64),
    LIVE_TAG                   VARCHAR(64),
    PROD                       VARCHAR(64),
    SALE_STATUS_COLOR          VARCHAR(64),
    HOUSE_TYPE_COLOR           VARCHAR(64),
    TOTAL_PRICE_START          VARCHAR(64),
    TOTAL_PRICE_START_UNIT     VARCHAR(64),
    AVG_PRICE_START            VARCHAR(64),
    AVG_PRICE_START_UNIT       VARCHAR(64),
    ON_TIME                    VARCHAR(64),
    PROJECT_DESC               VARCHAR(64),
    HAS_CAR_ACTIVITY           VARCHAR(64),
    IS_NEW_SALE                VARCHAR(64),
    FB_EXPO_ID                 VARCHAR(64),
    APP_DETAIL_URL             VARCHAR(256),
    FILTER_DESC                VARCHAR(64),
    URL                        VARCHAR(64),
    TAGS                       VARCHAR(256),
    DEVELOPER_COMPANY          VARCHAR(256),
    PROPERTY_COMPANY           VARCHAR(256),
    CREATED_DATETIME           DATETIME NOT NULL COMMENT '创建时间',
    LAST_MODIFIED_DATETIME     DATETIME NOT NULL COMMENT '修改时间',
    PRIMARY KEY (ID)
) COMMENT = '楼盘';